# Generated by Django 4.1.1 on 2022-09-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("speed", models.IntegerField(default=0)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
